apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spmonitor-tls-secret
  namespace: default
spec:
  dnsNames:
    - ## REDACTED ##
    - ## REDACTED ##
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: spmonitor-tls-secret
  usages:
    - digital signature
    - key encipherment