kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mimir-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.mimir.storage.capacity }}