apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
data:
  adminUser: {{ .Values.grafana.credentials.adminUser | b64enc }}
  adminPassword: {{ .Values.grafana.credentials.adminPassword | b64enc }}