apiVersion: v1
kind: Secret
metadata:
  name: minio-root-access
data:
  rootUser: {{ .Values.minio.credentials.rootUser | b64enc }}
  rootPassword: {{ .Values.minio.credentials.rootPassword | b64enc }}