{
 "title": "SPMonitor SP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "memUse - AM-DrivingLicenseManagement",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"am-drivinglicensemanagement.*\"}) by (pod) / 1e+9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memUse - AM-DrivingLicenseManagement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"am-drivinglicensemanagement.*\"}) by (pod) / 1e+9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memUse - SPMonitor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_usage_bytes{pod=~\"spmonitor.*\"}) by (pod) / 1e+9)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memUse - SPMonitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(sum(container_memory_usage_bytes{pod=~\"spmonitor.*\"}) by (pod) / 1e+9)"
    }
   ]
  },
  {
   "title": "memUse - Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "memUse - Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  }
 ]
}