apiVersion: v2
name: spmonitor
description: SPMonitor Helm Chart
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: grafana
    version: "6.*"
    repository: https://grafana.github.io/helm-charts
  - name: prometheus
    version: "22.*"
    repository: https://prometheus-community.github.io/helm-charts
  - name: spmonitor-mimir
    version: "0.1.0"
    repository: https://timengbrocks.github.io/spmonitor-mimir
    condition: persistency.enabled
  - name: minio
    version: "5.*"
    repository: https://charts.min.io/
    condition: persistency.enabled